# Generated by Django 5.1.7 on 2025-03-12 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='colors/')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Body_kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Discs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Restyling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Spoiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Tinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel')),
            ],
        ),
    ]
