# Generated by Django 5.1.7 on 2025-03-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(max_length=255, upload_to='brands/'),
        ),
    ]
