# Generated by Django 5.1.7 on 2025-03-12 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_brand_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bumper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RearBumper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SideSkirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel')),
            ],
        ),
    ]
