# Generated by Django 5.1.7 on 2025-03-12 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bumper_rearbumper_sideskirt_wing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheel',
            name='model',
        ),
        migrations.RemoveField(
            model_name='wing',
            name='model',
        ),
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(max_length=255, upload_to='brands/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='bumper',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='bumper',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/', verbose_name='3D модель бампера'),
        ),
        migrations.AlterField(
            model_name='bumper',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название бампера'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/', verbose_name='3D модель'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='color',
            name='img',
            field=models.ImageField(upload_to='colors/', verbose_name='Изображение цвета'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='discs',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='discs',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/', verbose_name='3D модель диска'),
        ),
        migrations.AlterField(
            model_name='discs',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название диска'),
        ),
        migrations.AlterField(
            model_name='rearbumper',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='rearbumper',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/', verbose_name='3D модель заднего бампера'),
        ),
        migrations.AlterField(
            model_name='rearbumper',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название заднего бампера'),
        ),
        migrations.AlterField(
            model_name='restyling',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='restyling',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/', verbose_name='3D модель рестайлинга'),
        ),
        migrations.AlterField(
            model_name='restyling',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название рестайлинга'),
        ),
        migrations.AlterField(
            model_name='sideskirt',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='sideskirt',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/', verbose_name='3D модель порога'),
        ),
        migrations.AlterField(
            model_name='sideskirt',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название порога'),
        ),
        migrations.AlterField(
            model_name='spoiler',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='spoiler',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/', verbose_name='3D модель спойлера'),
        ),
        migrations.AlterField(
            model_name='spoiler',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название спойлера'),
        ),
        migrations.AlterField(
            model_name='tinting',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='tinting',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/', verbose_name='3D модель тонировки'),
        ),
        migrations.AlterField(
            model_name='tinting',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название тонировки'),
        ),
        migrations.DeleteModel(
            name='Body_kit',
        ),
        migrations.DeleteModel(
            name='Wheel',
        ),
        migrations.DeleteModel(
            name='Wing',
        ),
    ]
